### ISSUE TITLE
Check and study the features google vision offers

### ISSUE THREAD

**Issue by ameeramer** [TechnionYP5779/Testock#238]
We should check and see what features google vision offers us.

Main questions:

- Can we use google vision to split image into blocks with labels?
- Can it detect digits in handwriting?

**Comment by moshesab** [comment]
- The Google vision API does not support a division of an image into block, but only labeling the whole image.
- Handwritten text detection is actually supplied by the API but does not work well on digits. Especially in the case of handwritten grades since they are usually written very sloppily. 

We might explore the "Crop Hint" tool which suppose to crop an image only in the main object of it (for example where a man stands).
