### ISSUE TITLE
Need to decide which display language to use

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/Testock#33]
According to what we have now, the interface is in English.
I think we might want to discuss it since our targeted audience use Hebrew, and also the content we store will be in Hebrew. The UG database of courses we will want to use is also in Hebrew.

What do you think?

**Comment by maxcalderon1997** [comment]
i think english is better. it doesnt matter that the content is in hebrew. for example i use facebook in english but the content is in hebrew

**Comment by moshesab** [comment]
In my opinion, Testock should be in Hebrew since our target audience is students from all faculties in Technion. We know that our faculty (CS) is trying to avoid Hebrew in official platforms for reasonable reasons, but this is not the case in other faculties, especially not in first year. 
As we can see for example the Moodle framework is all in Hebrew, and I don't see a reason to exceed that.
In addition, one of our first targets is to attract students to consume our service and to encourage them to upload their tests' scans, ask and answer questions etc. I think Hebrew platform will achieve this better.

**Comment by menhel** [comment]
I think the site should be multilingual. Just like Moodle (@moshesab), it should allow the student to choose the language of it.
That's a feature we will have to implement later on though, so for the meantime, let's stick with English (and the RTL layout we are already showing), and change it in one of the future sprints.

**Comment by yuvalron** [comment]
Start with English, add Hebrew later

**Comment by ron4548** [comment]
According to our current customer, English is good.
